# -----------------------------------------------------------------------------
# @author    STM32Cube bundle system
# -----------------------------------------------------------------------------
# @attention
#
# Copyright (c) 2025 STMicroelectronics.
# All rights reserved.
#
# This software is licensed under terms that can be found in the LICENSE file
# in the root directory of this software component.
# If no LICENSE file comes with this software, it is provided AS-IS.
#
# -----------------------------------------------------------------------------

# This file describes STMicroelectronics Arm Clang Toolchain.
#
#   - Applies to toolchain: STMicroelectronics Arm Clang Toolchain 19.1.6 and greater

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

# Some target device related default CLANG settings
set(CLANG_MFPU "none")
set(CLANG_MFLOATABI "soft")

if(CMSIS_Dcore STREQUAL "Cortex-M0")
  set(CLANG_ARCH "armv6m")
  set(CLANG_ARCH_SUFFIX "_soft_nofp")
  set(CLANG_MCPU "cortex-m0")
elseif(CMSIS_Dcore STREQUAL "Cortex-M0+")
  set(CLANG_ARCH "armv6m")
  set(CLANG_ARCH_SUFFIX "_soft_nofp")
  set(CLANG_MCPU "cortex-m0plus")
elseif(CMSIS_Dcore STREQUAL "Cortex-M1")
  set(CLANG_ARCH "armv6m")
  set(CLANG_ARCH_SUFFIX "_soft_nofp")
  set(CLANG_MCPU "cortex-m1")
elseif(CMSIS_Dcore STREQUAL "Cortex-M3")
  set(CLANG_ARCH "armv7m")
  set(CLANG_ARCH_SUFFIX "_soft_nofp")
  set(CLANG_MCPU "cortex-m3")
elseif(CMSIS_Dcore STREQUAL "Cortex-M4")
  set(CLANG_ARCH "armv7em")
  if(CMSIS_Dfpu STREQUAL "SP_FPU")
    set(CLANG_ARCH_SUFFIX "_hard_fpv4_sp_d16")
    set(CLANG_MCPU "cortex-m4")
    set(CLANG_MFPU "fpv4-sp-d16")
    set(CLANG_MFLOATABI "hard")
  else()
    set(CLANG_ARCH_SUFFIX "_soft_nofp")
    set(CLANG_MCPU "cortex-m4")
  endif()
elseif(CMSIS_Dcore STREQUAL "Cortex-M7")
  set(CLANG_ARCH "armv7em")
  if(CMSIS_Dfpu STREQUAL "DP_FPU")
    set(CLANG_ARCH_SUFFIX "_hard_fpv5_d16")
    set(CLANG_MCPU "cortex-m7")
    set(CLANG_MFPU "fpv5-d16")
    set(CLANG_MFLOATABI "hard")
  elseif(CMSIS_Dfpu STREQUAL "SP_FPU")
    set(CLANG_ARCH_SUFFIX "_hard_fpv4_sp_d16")
    set(CLANG_MCPU "cortex-m7")
    set(CLANG_MFPU "fpv5-sp-d16")
    set(CLANG_MFLOATABI "hard")
  else()
    set(CLANG_ARCH_SUFFIX "_soft_nofp")
    set(CLANG_MCPU "cortex-m7")
  endif()
elseif(CMSIS_Dcore STREQUAL "Cortex-M23")
  set(CLANG_ARCH "armv6m")
  set(CLANG_ARCH_SUFFIX "_soft_nofp")
  set(CLANG_MCPU "cortex-m23")
elseif(CMSIS_Dcore STREQUAL "Cortex-M33")
  set(CLANG_ARCH "armv8m.main")
  if(CMSIS_Dfpu STREQUAL "SP_FPU")
    set(CLANG_ARCH_SUFFIX "_hard_fp")
    if(CMSIS_Ddsp STREQUAL "DSP")
      set(CLANG_MCPU "cortex-m33")
    else()
      set(CLANG_MCPU "cortex-m33+nodsp")
    endif()
    set(CLANG_MFPU "fpv5-sp-d16")
    set(CLANG_MFLOATABI "hard")
  else()
    set(CLANG_ARCH_SUFFIX "_soft_nofp")
    if(CMSIS_Ddsp STREQUAL "DSP")
      set(CLANG_MCPU "cortex-m33")
    else()
      set(CLANG_MCPU "cortex-m33+nodsp")
    endif()
  endif()
elseif(CMSIS_Dcore STREQUAL "Cortex-M35P")
  set(CLANG_ARCH "armv8m.main")
  if(CMSIS_Dfpu STREQUAL "SP_FPU")
    set(CLANG_ARCH_SUFFIX "_hard_fp")
    if(CMSIS_Ddsp STREQUAL "DSP")
      set(CLANG_MCPU "cortex-m35p")
    else()
      set(CLANG_MCPU "cortex-m35p+nodsp")
    endif()
    set(CLANG_MFPU "fpv5-sp-d16")
    set(CLANG_MFLOATABI "hard")
  else()
    set(CLANG_ARCH_SUFFIX "_soft_nofp")
    if(CMSIS_Ddsp STREQUAL "DSP")
      set(CLANG_MCPU "cortex-m35p")
    else()
      set(CLANG_MCPU "cortex-m35p+nodsp")
    endif()
  endif()
elseif(CMSIS_Dcore STREQUAL "Cortex-M52")
  set(CLANG_ARCH "armv8.1m.main")
  if(CMSIS_Dfpu STREQUAL "NO_FPU")
    if(MVE STREQUAL "NO_MVE")
      set(CLANG_ARCH_SUFFIX "_soft_nofp_nomve")
      set(CLANG_MCPU "cortex-m52+nofp+nomve")
    else()
      set(CLANG_ARCH_SUFFIX "_hard_nofp_mve")
      set(CLANG_MCPU "cortex-m52+nofp")
      set(CLANG_MFLOATABI "hard")
    endif()
  else()
    set(CLANG_ARCH_SUFFIX "_hard_fp")
    if(MVE STREQUAL "NO_MVE")
      set(CLANG_MCPU "cortex-m52+nomve")
    elseif(MVE STREQUAL "MVE")
      set(CLANG_MCPU "cortex-m52+nomve.fp")
    else()
      set(CLANG_MCPU "cortex-m52")
    endif()
    set(CLANG_MFPU "fpv5-sp-d16")
    set(CLANG_MFLOATABI "hard")
  endif()
elseif(CMSIS_Dcore STREQUAL "Cortex-M55")
  set(CLANG_ARCH "armv8.1m.main")
  if(CMSIS_Dfpu STREQUAL "NO_FPU")
    if(MVE STREQUAL "NO_MVE")
      set(CLANG_ARCH_SUFFIX "_soft_nofp_nomve")
      set(CLANG_MCPU "cortex-m55+nofp+nomve")
    else()
      set(CLANG_ARCH_SUFFIX "_hard_nofp_mve")
      set(CLANG_MCPU "cortex-m55+nofp")
      set(CLANG_MFLOATABI "hard")
    endif()
  else()
    set(CLANG_ARCH_SUFFIX "_hard_fp")
    if(MVE STREQUAL "NO_MVE")
      set(CLANG_MCPU "cortex-m55+nomve")
    elseif(MVE STREQUAL "MVE")
      set(CLANG_MCPU "cortex-m55+nomve.fp")
    else()
      set(CLANG_MCPU "cortex-m55")
    endif()
    set(CLANG_MFPU "fpv5-sp-d16")
    set(CLANG_MFLOATABI "hard")
  endif()
elseif(CMSIS_Dcore STREQUAL "Cortex-M85")
  set(CLANG_ARCH "armv8.1m.main")
  if(CMSIS_Dfpu STREQUAL "NO_FPU")
    if(MVE STREQUAL "NO_MVE")
      set(CLANG_ARCH_SUFFIX "_soft_nofp_nomve")
      set(CLANG_MCPU "cortex-m85+nofp+nomve")
    else()
      set(CLANG_ARCH_SUFFIX "_hard_nofp_mve")
      set(CLANG_MCPU "cortex-m85+nofp")
      set(CLANG_MFLOATABI "hard")
    endif()
  else()
    set(CLANG_ARCH_SUFFIX "_hard_fp")
    if(MVE STREQUAL "NO_MVE")
      set(CLANG_MCPU "cortex-m85+nomve")
    elseif(MVE STREQUAL "MVE")
      set(CLANG_MCPU "cortex-m85+nomve.fp")
    else()
      set(CLANG_MCPU "cortex-m85")
    endif()
    set(CLANG_MFPU "fpv5-sp-d16")
    set(CLANG_MFLOATABI "hard")
  endif()
elseif(CMSIS_Dcore STREQUAL "Cortex-A5")
  set(CLANG_ARCH "armv7")
  if(CMSIS_Dfpu STREQUAL "DP_FPU")
    set(CLANG_MCPU "cortex-a5+nosimd")
    set(CLANG_MFPU "vfpv4-d16")
    set(CLANG_MFLOATABI "hard")
  else()
    set(CLANG_MCPU "cortex-a5+nosimd+nofp")
  endif()
elseif(CMSIS_Dcore STREQUAL "Cortex-A7")
  set(CLANG_ARCH "armv7")
  if(CMSIS_Dfpu STREQUAL "DP_FPU")
    set(CLANG_MCPU "cortex-a7+nosimd")
    set(CLANG_MFPU "vfpv4-d16")
    set(CLANG_MFLOATABI "hard")
  else()
    set(CLANG_MCPU "cortex-a7+nosimd+nofp")
  endif()
elseif(CMSIS_Dcore STREQUAL "Cortex-A9")
  set(CLANG_ARCH "armv7")
  if(CMSIS_Dfpu STREQUAL "DP_FPU")
    set(CLANG_MCPU "cortex-a9+nosimd")
    set(CLANG_MFPU "vfpv3-d16")
    set(CLANG_MFLOATABI "hard")
  else()
    set(CLANG_MCPU "cortex-a9+nosimd+nofp")
  endif()
elseif(CMSIS_Dcore STREQUAL "Cortex-A35")
  set(CLANG_ARCH "armv8")
  if(CMSIS_Dfpu STREQUAL "DP_FPU")
    set(CLANG_MCPU "cortex-a35")
  else()
    set(CLANG_MCPU "cortex-a35+nofp")
  endif()
elseif(CMSIS_Dcore STREQUAL "Cortex-A53")
  set(CLANG_ARCH "armv8")
  if(CMSIS_Dfpu STREQUAL "DP_FPU")
    set(CLANG_MCPU "cortex-a53")
  else()
    set(CLANG_MCPU "cortex-a53+nofp")
  endif()
elseif(CMSIS_Dcore STREQUAL "Cortex-A55")
  set(CLANG_ARCH "armv8")
  if(CMSIS_Dfpu STREQUAL "DP_FPU")
    set(CLANG_MCPU "cortex-a55")
  else()
    set(CLANG_MCPU "cortex-a55+nofp")
  endif()
elseif(CMSIS_Dcore STREQUAL "Cortex-A57")
  set(CLANG_ARCH "armv8")
  if(CMSIS_Dfpu STREQUAL "DP_FPU")
    set(CLANG_MCPU "cortex-a57")
  else()
    set(CLANG_MCPU "cortex-a57+nofp")
  endif()
endif()

if(CLANG_ARCH STREQUAL "armv8")
  set(CLANG_TARGET "aarch64-st-none-elf")
  set(CPU_FLAGS --target=${CLANG_TARGET} -mcpu=${CLANG_MCPU})
else()
  if(CLANG_MFLOATABI STREQUAL "hard")
    set(CLANG_TARGET "${CLANG_ARCH}-st-none-eabihf")
  else()
    set(CLANG_TARGET "${CLANG_ARCH}-st-none-eabi")
  endif()
  set(CPU_FLAGS --target=${CLANG_TARGET} -mcpu=${CLANG_MCPU} -mfloat-abi=${CLANG_MFLOATABI})
endif()

if(CMSIS_Dendian STREQUAL "Little-endian")
  set(CPU_FLAGS ${CPU_FLAGS} -mlittle-endian)
elseif(CMSIS_Dendian STREQUAL "Big-endian")
  set(CPU_FLAGS ${CPU_FLAGS} -mbig-endian)
endif()

set(CPU_FLAGS ${CPU_FLAGS} -mthumb)

# Some C Pre-Processor related default CLANG settings 
if(CMSIS_Dsecure STREQUAL "Secure" OR CMSIS_Dsecure STREQUAL "Secure-only")
  set(SECURE_FLAGS "-mcmse")
endif()

# Some default CLANG settings
if (STARM_TOOLCHAIN_CONFIG STREQUAL "STARM_NEWLIB")
  # PICOLIBC C library as default
  # NEWLIB C library as end user option
  set(TOOLCHAIN_MULTILIBS "--config=newlib.cfg")
endif()

set(FLAGS                           "-Wno-comment ${TOOLCHAIN_MULTILIBS}")
set(CPP_FLAGS                       "${FLAGS} -fno-rtti -fno-exceptions -fno-threadsafe-statics")

set(CMAKE_C_FLAGS                   ${FLAGS})
set(CMAKE_CXX_FLAGS                 ${CPP_FLAGS})

set(TOOLCHAIN_PREFIX                starm-)
set(CMAKE_C_COMPILER                "${TOOLCHAIN_PREFIX}clang")
set(CMAKE_ASM_COMPILER              "${TOOLCHAIN_PREFIX}clang")
set(CMAKE_CXX_COMPILER              "${TOOLCHAIN_PREFIX}clang++")
set(CMAKE_OBJCOPY                   "${TOOLCHAIN_PREFIX}objcopy")
set(CMAKE_SIZE                      "${TOOLCHAIN_PREFIX}size")

set(CMAKE_EXECUTABLE_SUFFIX_ASM     ".elf")
set(CMAKE_EXECUTABLE_SUFFIX_C       ".elf")
set(CMAKE_EXECUTABLE_SUFFIX_CXX     ".elf")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)